name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build docker image for dev testing
        run: docker build -t mayankgupta804/react-test -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true mayankgupta804/react-test npm test

      - name: Build docker image for prod
        run: docker build -t mayankgupta804/react Dockerfile .

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: react-frontend
          environment_name: React-frontend-env
          existing_bucket_name: elasticbeanstalk-us-east-2-336168347913
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
